version: '3'
services:
  prisma_example:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            host: 192.168.65.155
            database: prisma_example
            port: 3306
            user: root
            password: mysql@root
            migrations: false
